## libvirt-nat
##
## Assumptions (at this time):
##   + PublicNet is required with unrestricted internet access
##   + use RHEL 7.7 or later
##   + use Ansible 2.9 or later
##

##
## First character of variable defines scope
## and should help tracking where it is defined.
##
##  g_Name - global: declared in this file
##
##  h_Name - host: declared in host inventory OR
##                 in a [hostname:vars] block
##
##  p_Name - play: declared as part of a play
##

##
## NOTE: paths to additional customizable variable files are 
##       declared in playbooks/group_vars/all/var_config.yml
##

[all:vars]

##
## ----------------------------------------
## General Parameters
##

## (Optional) Who is the POC owner
g_owner = "Foo Bar"

## (Optional) What is the POC location
g_location = "Dallas"

## Configure the student name as this
g_studentName = "cloud-user"

## Your OCP Cluster Name
g_clusterName = "ocp"

## Your OCP Cluster Wildcard Name
g_wildcardName = "apps"

## Your OCP Cluster Creds Dir
g_credsDir = "/root/ocp-{{ g_clusterName}}"

##
## ----------------------------------------
## g_clusterVIP
##
##   If you are planning to run a loadbalancer (haproxy)
##   on a host other than the bastion (ie: the virt-host perhaps)
##   specify the cluster virtual IP (VIP).  This is only
##   used to create an additional haproxy.cfg and does
##   not impact the cluster configuration or deployment
##

g_clusterVIP = "192.168.1.29"

##
## ----------------------------------------
## Proxy settings (affects playbooks and openshift config)
##
##   Examples:
##     g_http_proxy = httpProxy: http://<username>:<pswd>@<ip>:<port> 
##     g_https_proxy = httpsProxy: http://<username>:<pswd>@<ip>:<port> 
##     g_no_proxy = noProxy: example.com 

g_http_proxy  = ""
g_https_proxy = ""
g_no_proxy    = ""

##
## ----------------------------------------
## Networking Parameters
##

## Configure the public (primary) network
g_publicNet     = "True"
g_publicDomain  = "example.com"
g_pubNET        = "192.168.123.0"
g_pubNM         = "255.255.255.0"
g_pubPREFIX     = "24"
g_pubGW         = "192.168.123.1"
g_pubDNS        = "192.168.123.1"
g_pubNTP        = "192.168.123.160"
g_pubFQDN       = "{{ g_clusterName }}.{{ g_publicDomain }}"

## Configure the private (secondary) network
g_privateNet    = "False"
g_privateDomain = "private.example.com"
g_priNET        = "10.0.0.0"
g_priNM         = "255.255.255.0"
g_priPREFIX     = ""
g_priGW         = ""
g_priDNS        = ""
g_priNTP        = ""

##
## ----------------------------------------
##
## Optional Local Services that can be enabled on bastion
##
##   DNS          - provided by dnsmasq
##   DHCP & PXE   - provided by dhcp-server
##   LOADBALANCER - provided by haproxy
##   MATCHBOX     - service to provide artifacts to RHCOS ( installation automation)
##   NFS          - configure NFS server for persistent storage
##   NTP          - configure cluster to use bastion as NTP server
##   REPOSYNC     - have bastion sync content and create a repo
##
##

g_useDNS          = "True"
g_useDHCP         = "True"
g_usePXE          = "True"
g_useHAPROXY      = "True"
g_useHAPROXY_VIP  = "True"
g_useMATCHBOX     = "True"
g_useNFS          = "True"
g_useNTP          = "True"
g_useREPOSYNC     = "False"

## Configure DNS wildcard on bastion host
g_useDNSwildcard = "True"

##
## ----------------------------------------
## NFS server variables

g_nfsExport = "/home/nfs-{{ g_clusterName }}"

##
## ----------------------------------------
##
## HTTPD Parameters 
##
##     http server on virthost to
##     support kickstart and repo
##   

g_http_port = "8008"

##
## ----------------------------------------
##
## This has the effect of changing the default domainname so
## we won't have to specify FQDN in host vars section below
##

ansible_host="{{ inventory_hostname }}.{{ g_pubFQDN }}"

##
## ----------------------------------------
## HOSTGROUP VARS

[myVirthost:vars]

## We are running the playbooks on the baremetal virthost

## -----------------

[myBastion:vars]

ansible_connection = "local"

h_hwPROF = "kvm_vda" 
h_rsPROF = "bastion"
h_ksPROF = "rhel8_lvm"


## -----------------

[myBootstrap:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "sml"
h_ksPROF = "" 

## h_mBoxDev : default is ''
##   If RHCOS is not detecting the right boot device, you can be specific
##   by adding and setting the full device path.  In my lab, vda needs to be
##   specified, so for now that's the default.

h_mBoxDev = "vda"

## -----------------

[myMasters:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "med"
h_ksPROF = ""
h_mBoxDev = "vda"

## -----------------

[myWorkers:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "sml"
h_ksPROF = ""
h_mBoxDev = "vda"

##
## ----------------------------------------
## HOST VARS

[myVirthost]
##virthost  h_pubMAC="" h_pubIP=""

[myBastion]
bastion   h_pubMAC="2c:c2:60:30:c1:c1" h_pubIP="192.168.123.160" 

[myBootstrap]
bootstrap h_pubMAC="2c:c2:60:43:c2:c2" h_pubIP="192.168.123.161" 

[myMasters]
master-0  h_pubMAC="2c:c2:60:02:c3:c3" h_pubIP="192.168.123.162" h_etcdName="etcd-0"
master-1  h_pubMAC="2c:c2:60:60:c4:c4" h_pubIP="192.168.123.163" h_etcdName="etcd-1"
master-2  h_pubMAC="2c:c2:60:4d:c5:c5" h_pubIP="192.168.123.164" h_etcdName="etcd-2"

[myWorkers]
worker-0  h_pubMAC="2c:c2:60:4d:c6:c6" h_pubIP="192.168.123.165" 
worker-1  h_pubMAC="2c:c2:60:4d:c7:c7" h_pubIP="192.168.123.166" 
