##
## ----------------------------------------
##
## Red Hat CoreOS Parameters
##
##   Declare sources & versions of RHCOS
##

g_rhcos_src:       "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.4/4.4.3"
g_rhcos_initramfs: "rhcos-4.4.3-x86_64-installer-initramfs.x86_64.img"
g_rhcos_kernel:    "rhcos-4.4.3-x86_64-installer-kernel-x86_64"
g_rhcos_bios:      "rhcos-4.4.3-x86_64-metal.x86_64.raw.gz"
g_rhcos_iso:       "rhcos-4.4.3-x86_64-installer.x86_64.iso"

