##
## Assumptions (at this time):
##   + PublicNet is required with unrestricted internet access
##   + use RHEL 7.7 or later
##   + use Ansible 2.9 or later
##   + dhcp/dnsmasq has been disabled in libvirt's default bridged (nat) network
##       - virsh net-edit default
##       - remove <dhcp .... .... /dhcp> block 
##       - restart the network  `virsh net-{destroy,start} default`
##

##
## First character of variable defines scope
## and should help tracking where it is defined.
##
##  g_Name - global: declared in this file
##
##  h_Name - host: declared in host inventory OR
##                 in a [hostname:vars] block
##
##  p_Name - play: declared as part of a play
##

[all:vars]

## (Optional) Who is the POC owner
g_owner = "Christoph"

## (Optional) What is the POC location
g_location = "COS"

## Configure the student name as this
g_studentName = "student"

## Configure the public (primary) network
g_publicNet     = "True"
g_publicDomain  = "vzbi.com"
g_pubNET        = "166.34.184.0"
g_pubNM         = "255.255.252.0"
g_pubGW         = "166.34.187.254"
g_pubDNS        = "166.37.162.103"
g_pubNTP        = "166.37.162.103,166.37.218.90,166.37.130.87"
g_pubFQDN       = "{{ g_clusterName }}.{{ g_publicDomain }}"

## Configure the private (secondary) network
g_privateNet    = "False"
g_privateDomain = "private.example.com"
g_priNET        = "10.0.0.0"
g_priNM         = "255.255.255.0"
g_priGW         = ""
g_priDNS        = ""

## Your OCP Cluster Name
g_clusterName = "cosocp"

## Your OCP Cluster Wildcard Name
g_wildcardName = "apps"

##
## ----------------------------------------
##
## Optional Local Services that can be enabled on bastion
##
##   DNS          - provided by dnsmasq
##   DHCP & PXE   - provided by dhcp-server
##   LOADBALANCER - provided by haproxy
##   MATCHBOX     - service to provide artifacts to RHCOS ( installation automation)
##
##   NOTE: for iPXE support, g_httpPort
##         and g_httpsPort are required
##

g_useDNS      = "True"
g_useDHCP     = "True"
g_usePXE      = "True"
g_useHAPROXY  = "True"
g_useMATCHBOX = "True"
g_useNFS      = "True"
g_useNTP      = "True"
g_useREPOSYNC = "False"

## Configure DNS wildcard on bastion host
g_useDNSwildcard = "True"

##
## ----------------------------------------
## NFS server variables

g_nfsExport = "/home/nfs"

##
## ----------------------------------------
##
## Matchbox Parameters
##   

g_matchbox_port = "8080"

##
## ----------------------------------------
##
## This has the effect of changing the default domainname so
## we won't have to specify FQDN in host vars section below
##

ansible_host="{{ inventory_hostname }}.{{ g_pubFQDN }}"

##
## ----------------------------------------
##

[myVirthost:vars]

## We are running the playbooks on the baremetal virthost
#ansible_connection = "local"

[myBastion:vars]

## We are running the playbooks on the bastion node
ansible_connection = "local"

##
## ----------------------------------------
##

[myVirthost]
virthost  h_pubMAC="00:00:00:00:00:00" h_pubIP="0.0.0.0"

[myBastion]
cosdrh802v  h_pubMAC="00:50:56:8b:cc:d2" h_pubIP="166.34.187.198"  h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="bastion"

[myBootstrap]
bootstrap   h_pubMAC="00:50:56:8b:ee:e7" h_pubIP="166.34.187.58"   h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="med"

[myMasters]
master0     h_pubMAC="00:50:56:8b:22:7a" h_pubIP="166.34.187.92"   h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="med" h_etcdName="etcd-0" 
master1     h_pubMAC="00:50:56:8b:7f:89" h_pubIP="166.34.187.90"   h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="med" h_etcdName="etcd-1" 
master2     h_pubMAC="00:50:56:8b:f8:7c" h_pubIP="166.34.187.67"   h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="med" h_etcdName="etcd-2" 

[myWorkers]
worker0     h_pubMAC="00:50:56:8b:7a:cd" h_pubIP="166.34.187.60"   h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="sml"
#worker1     h_pubMAC="00:00:00:00:00:00" h_pubIP="166.34.187.000" h_priMAC="00:00:00:00:00:00" h_priIP="0.0.0.0" h_hwPROF="vmware_sda" h_rsPROF="sml"

