
## ------------------------------
## KVM/Libvirt Config Options
##
##     Parameters for the Virtual Machine Host (libvirt)
##

##
## Profile: NAT bridge
##

g_kvmhost_ip:   "192.168.123.1"
g_http_port:    "8008"
g_cockpit_port: "9090"

kvm_cfg: 

  enable_nested_virt: false

  http_port:    "{{ g_http_port }}"
  cockpit_port: "{{ g_cockpit_port }}"
 
  qcow_dir:     "/home/virt-images"
  ks_url:       "http://{{ g_kvmhost_ip }}:{{ g_http_port }}/ks"

  network:
    name:       "virbr-{{ g_clusterName }}"
    bridge:     "virbr-{{ g_clusterName }}"
    fwd_type:   "nat"
    dev:        "eno1"
    ipv4:
      addr:     "{{ g_kvmhost_ip }}/{{ g_pubPREFIX }}"
      nm:       "{{ g_pubNM }}"

  iso:
    dir:        "/var/www/html/iso"
    name:       "rhel-8.1-x86_64-dvd.iso"
    mount:      "/var/www/html/repo"

  repo:
    repo1 : 
      name: "rhel-8-baseos-rpms"
      url:  "http://{{ g_kvmhost_ip }}:{{ g_http_port }}/repo/BaseOS"
    repo2 : 
      name: "rhel-8-appstream-rpms"
      url:  "http://{{ g_kvmhost_ip }}:{{ g_http_port }}/repo/AppStream"

kvm_deploy_plan:

  ## PRE/POST INSTALL SCRIPTS BEFORE AND AFTER DEPLOY
  ##
  ##   pre_install:       STR complete executable shell (PWD: is project directory) 
  ##   post_install:      STR complete executable shell (PWD: is project directory) 

  pre_install:  ""
  post_install: "ansible-playbook -i ./config/master-config.yml -e @./config/libvirt-config.yml -f 10 --tags finish ./playbooks/bastion-setup.yml"

  ## 
  ## each pass must define the following:
  ##
  ##   hostgroup:         STR ansible hostgroup to act on 
  ##   inject_sshkey:     T/F create a ssh key to enable ansible on client 
  ##   wait_for_shutdown: T/F wait for shutdown before install-02 (postconfig)
  ##   post_config:       T/F run actions in install-02 (postconfig)
  ##
  ##   # PRE/POST INSTALL SCRIPTS BEFORE AND AFTER EACH HOSTGROUP
  ##   pre_install:       STR complete executable shell (PWD: is project directory) 
  ##   post_install:      STR complete executable shell (PWD: is project directory) 
  ## 

  passes: 
    pass_1:
      hostgroup:          "myBastion"
      inject_sshkey:      True
      wait_for_shutdown:  True
      post_config:        True
      pre_install:        ""
      post_install:       "ansible-playbook -i ./config/master-config.yml -e @./config/libvirt-config.yml -f 10  ./playbooks/libvirt-postinstall-bastion.yml"

    pass_2:
      hostgroup:          "myBootstrap"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -e @./config/libvirt-config.yml -f 10  ./playbooks/libvirt-preinstall-bootstrap.yml"
      post_install:       ""

    pass_3:
      hostgroup:          "myMasters"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -e @./config/libvirt-config.yml -f 10  ./playbooks/libvirt-preinstall-masters.yml"
      post_install:       ""

    pass_4:
      hostgroup:          "myWorkers"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -e @./config/libvirt-config.yml -f 10  ./playbooks/libvirt-preinstall-workers.yml"
      post_install:       ""

