
## ------------------------------
## KVM/Libvirt Config Options
##
##     Parameters for the Virtual Machine Host (libvirt)
##

##
## Profile: NAT bridge
##

# virt-host addr in private network
g_kvmhost_ip:   "192.168.123.1"

# httpd,kickstart,repo service port
g_http_port:    "8008"                  

# cockpit defaults to 9090, but you can change it
g_cockpit_port: "9090"

kvm_cfg: 

  enable_nested_virt: false

  http_port:    "{{ g_http_port }}"
  cockpit_port: "{{ g_cockpit_port }}"
 
  qcow_dir:     "/home/virt-images"

  network:
    name:       "virbr-{{ g_clusterName }}"
    bridge:     "virbr-{{ g_clusterName }}"
    fwd_type:   "nat"
    dev:        "eno1"
    ipv4:
      addr:     "{{ g_kvmhost_ip }}/{{ g_pubPREFIX }}"
      nm:       "{{ g_pubNM }}"

  kickstart:
    dir: "/var/www/html/ks"
    url: "http://{{ g_kvmhost_ip }}:{{ g_http_port }}/ks"

  iso:
    dir:        "/home/iso"

  repo:
    dir: "/var/www/html/repos"
    url: "http://{{ g_kvmhost_ip }}:{{ g_http_port }}/repos"

deployer_cfg:

  ## deployer hostname OR ip
  ip: "{{ g_kvmhost_ip }}"

  ## httpd,kickstart,repo service port
  http_port:    "8008"

  ## cockpit defaults to 9090, but you can change it
  cockpit_port: "9090"

  kickstart:
    dir: "/var/www/html/ks"
    url: "http://{{ g_kvmhost_ip }}:8008/ks"

  iso:
    dir: "/home/iso"

  repo:
    dir: "/var/www/html/repos"
    url: "http://{{ g_kvmhost_ip }}:8008/repos"

deployer_plan:

  ## PRE/POST INSTALL SCRIPTS BEFORE AND AFTER DEPLOY
  ##
  ##   pre_install:       STR complete executable shell (PWD: is project directory) 
  ##   post_install:      STR complete executable shell (PWD: is project directory) 

  pre_install:  ""
  post_install: "ansible-playbook -i ./config/master-config.yml -f 10 --tags finish ./playbooks/bastion-setup.yml"

  ## 
  ## each pass must define the following:
  ##
  ##   hostgroup:         STR ansible hostgroup to act on 
  ##   inject_sshkey:     T/F create a ssh key to enable ansible on client 
  ##   wait_for_shutdown: T/F wait for shutdown before install-02 (postconfig)
  ##   post_config:       T/F run actions in install-02 (postconfig)
  ##
  ##   # PRE/POST INSTALL SCRIPTS BEFORE AND AFTER EACH HOSTGROUP
  ##   pre_install:       STR complete executable shell (PWD: is project directory) 
  ##   post_install:      STR complete executable shell (PWD: is project directory) 
  ## 

  passes: 
    pass_1:
      hostgroup:          "myBastion"
      inject_sshkey:      True
      wait_for_shutdown:  True
      post_config:        True
      pre_install:        ""
      post_install:       "ansible-playbook -i ./config/master-config.yml -f 10  ./playbooks/libvirt-postinstall-bastion.yml"

    pass_2:
      hostgroup:          "myBootstrap"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -f 10  ./playbooks/libvirt-preinstall-bootstrap.yml"
      post_install:       ""

    pass_3:
      hostgroup:          "myMasters"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -f 10  ./playbooks/libvirt-preinstall-masters.yml"
      post_install:       ""

    pass_4:
      hostgroup:          "myWorkers"
      inject_sshkey:      False
      wait_for_shutdown:  False
      post_config:        False
      pre_install:       "ansible-playbook -i ./config/master-config.yml -f 10  ./playbooks/libvirt-preinstall-workers.yml"
      post_install:       ""

