## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook intends to do the heavy lifting of configuring the bastion-host based on the paremeters defined in the
##   ansible inventory (config).
##
##   It will install missing packages, pull (wget) openshift installer, rhcos, etc...
##
## Playbook Assumptions:
##     #1 you are executing this on the bastion-host
##     #2 you have configured and copied ssh-keys to itself.  Meaning, ssh root@localhost works without a password
##     #3 you have completed adjustments to ../configs/ocp4poc-default
##

---
- hosts: myBastion
  tasks:

  - name: "BASTION-NTP: package installation"
    yum: name=chrony state=installed

  - name: "BASTION-NTP: configure chrony as ntp server"
    replace:
      path: /etc/chrony.conf
      regexp: '^#(local stratum 10).*?$'
      replace: '\1'

  - name: "BASTION-NTP: restart service"
    service: name=chronyd state=restarted enabled=yes

  - name: "BASTION-NTP: add firewalld service rules"
    firewalld:
      service: ntp
      immediate: yes
      permanent: yes
      state: enabled

