## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook intends to do the heavy lifting of configuring the bastion-host based on the paremeters defined in the
##   ansible inventory (config).
##
##   It will install missing packages, pull (wget) openshift installer, rhcos, etc...
##
## Playbook Assumptions:
##     #1 you are executing this on the bastion-host
##     #2 you have configured and copied ssh-keys to itself.  Meaning, ssh root@localhost works without a password
##     #3 you have completed adjustments to ../configs/ocp4poc-default
##

---
- hosts: myBastion
  tasks:

  - name: "BASTION-DNS: package installation"
    yum: name=dnsmasq state=installed

  - name: "BASTION-DNS: clean cfg directory"
    shell:
      cmd: |
        if [[ -d "/etc/dnsmasq.d" ]] ; then rm -rf /etc/dnsmasq.d/* ; fi

  - name: "BASTION-DNS: deploy standard options"
    vars: 
      - p_nameServer:  "{{ g_pubDNS }}"
    template:
      src: "dnsmasq-standard-opts.j2"
      dest: "/etc/dnsmasq.d/30-standard-opts.conf"
      owner: root

  - name: "BASTION-DNS: deploy PUBLIC HOST configs"
    vars: 
      - p_item:     "{{ item }}"
      - p_name:     "{{ hostvars[item]['inventory_hostname_short']}}"
      - p_addr:     "{{ hostvars[item]['h_pubIP'] }}"
      - p_mac:      "{{ hostvars[item]['h_pubMAC'] }}"
      - p_etcdName: "{{ hostvars[item]['h_etcdName'] | default('') }}"
      - p_revAddr:  "{{ (p_addr.split('.'))[::-1]|join('.') }}"
      - p_netmask:  "{{ g_pubNM }}"
      - p_gateway:  "{{ g_pubGW'] }}"
      - p_domain:   "{{ g_clusterName }}.{{ g_publicDomain }}"
    when: g_publicNet == "True" 
    template:
      src: "dnsmasq-host-entry.j2"
      dest: "/etc/dnsmasq.d/50-dns-{{ p_domain }}-{{ p_name }}.conf"
      owner: root
      group: root
      mode: 644
    loop: "{{ groups['all'] }}"

  - name: "BASTION-DNS: deploy PRIVATE HOST configs"
    vars: 
      - p_item:     "{{ item }}"
      - p_name:     "{{ hostvars[item]['inventory_hostname_short']}}"
      - p_addr:     "{{ hostvars[item]['h_priIP'] }}"
      - p_mac:      "{{ hostvars[item]['h_priMAC'] }}"
      - p_etcdName: "{{ hostvars[item]['h_etcdName'] | default('') }}"
      - p_revAddr:  "{{ (p_addr.split('.'))[::-1]|join('.') }}"
      - p_netmask:  "{{ g_priNM }}"
      - p_gateway:  "{{ g_priGW }}"
      - p_domain:   "{{ g_clusterName }}.{{ g_privateDomain }}"
    when: g_privateNet == "True" 
    template:
      src: "dnsmasq-host-entry.j2"
      dest: "/etc/dnsmasq.d/50-dns-{{ p_domain }}-{{ p_name }}.conf"
      owner: root
      group: root
      mode: 644
    loop: "{{ groups['all'] }}"

  - name: "BASTION-DNS: deploy ETCD configs"
    vars: 
      - p_item:      "{{ item }}"
      - p_name:      "{{ hostvars[item]['inventory_hostname_short']}}"
      - p_addr:      "{{ hostvars[item]['h_pubIP'] }}"
      - p_etcdName:  "{{ hostvars[item]['h_etcdName'] | default('') }}"
      - p_domain:    "{{ g_clusterName }}.{{ g_publicDomain }}"
      - p_clusterName: "{{ g_clusterName }}"
    when:
      - p_etcdName != ""
    template:
      src: "dnsmasq-etcd-entry.j2"
      dest: "/etc/dnsmasq.d/45-etcd-{{ p_etcdName }}.conf"
      owner: root
      group: root
      mode: 644
    loop: "{{ groups['all'] }}"

  - name: "BASTION-DNS: deploy API config"
    vars: 
      - p_addr:      "{{ hostvars[item]['h_pubIP'] }}"
      - p_domain:    "{{ g_clusterName }}.{{ g_publicDomain }}"
      - p_revAddr:   "{{ (p_addr.split('.'))[::-1]|join('.') }}"
    when:
      - g_useDNS == "True" 
    template:
      src: "dnsmasq-api-entry.j2"
      dest: "/etc/dnsmasq.d/55-api-{{ g_clusterName }}.conf"
      owner: root
    loop: "{{ groups['myBastion'] }}"

  - name: "BASTION-DNS: deploy PUBLIC wildcard"
    vars: 
      - p_addr:      "{{ hostvars[item]['h_pubIP'] }}"
      - p_domain:    "{{ g_wildcardName }}.{{ g_clusterName }}.{{ g_publicDomain }}"
    when:
      - g_useDNSwildcard == "True"
    template:
      src: "dnsmasq-wildcard-entry.j2"
      dest: "/etc/dnsmasq.d/45-wildcard-{{ g_clusterName }}.conf"
      owner: root
    loop: "{{ groups['myBastion'] }}"


  - name: "BASTION-DNS: restart service"
    service: name=dnsmasq state=restarted enabled=yes

  - name: "BASTION-DNS: add firewalld service rules"
    firewalld:
      service: dns
      immediate: yes
      permanent: yes
      state: enabled

  ##
  ## This will loop through all ethernet interfaces and set DNS to localhost
  ##

  - name: "BASTION-DNS: fix resolv.conf to go localhost"
    shell:
      cmd: |
        nmcli con modify {{ item }} ipv4.dns 127.0.0.1
        if [[ -e /etc/sysconfig/network-scripts/ifcfg-{{item}} ]] ; then
          ifup {{ item }} 
        fi
    when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
    with_items:
      - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

