## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   Downloads and unpacks software for OCP installation
##

---
- hosts: myBastion
  tasks:

  - name: "BASTION-OPENSHIFT: Create ssh directory"
    file:
      path: /root/.ssh
      mode: "0700"
      state: directory

  - name: "BASTION-OPENSHIFT: test ssh key"
    stat: path="/root/.ssh/id_rsa.pub"
    register: test_ssh_key

  - name: "BASTION-OPENSHIFT: create ssh key"
    command: "ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa"
    when: test_ssh_key.stat.exists == false

  - name: "BASTION-OPENSHIFT: download ocp software [SRC: {{ ocp_assets[g_clusterVersion]['url'] }}]"
    environment:
      http_proxy: "{{ g_http_proxy }}"
      https_proxy: "{{ g_https_proxy }}"
    get_url:
      url: "{{ ocp_assets[g_clusterVersion]['url'] }}/{{ item }}"
      dest: "/usr/local/src/{{ item }}"
      mode: "0644"
    with_items:
      - "{{ ocp_assets[g_clusterVersion]['install_tar'] }}"
      - "{{ ocp_assets[g_clusterVersion]['client_tar'] }}"

  - name: "BASTION-OPENSHIFT: unpack ocp software"
    shell:
      cmd: |
        cd /usr/local/bin
        tar zxvf /usr/local/src/{{ item }}
    with_items:
      - "{{ ocp_assets[g_clusterVersion]['install_tar'] }}"
      - "{{ ocp_assets[g_clusterVersion]['client_tar'] }}"

  - name: "BASTION-OPENSHIFT: additional package installation"
    yum: name=bash-completion state=installed

  - name: "BASTION-OPENSHIFT: configure openshift bash completion"
    shell: 
      cmd: |
        /usr/local/bin/oc completion bash >> /etc/bash_completion.d/oc_completion
        /usr/local/bin/openshift-install completion bash >> /etc/bash_completion.d/openshift-install_completion

  ##
  ## Only execute tasks if workshop_lock == false
  ##

  - block:

      ## 
      ## Clean up installation artifacts
      ##

      - name: "BASTION-OPENSHIFT: Back-up openshift installation artifacts in {{ g_credsDir }}"
        shell:
          cmd: |
            if [[ -d "{{ g_credsDir }}" ]]; 
              then mv -f "{{ g_credsDir }}" "{{ g_credsDir }}".`date +"%Y%m%d-%R"`
            fi
          removes: "{{ g_credsDir }}"
    
      - name: "BASTION-OPENSHIFT: Clean-up kube artifacts in /root/.kube"
        file:
          path: "/root/.kube"
          state: absent
    
      - name: "BASTION-OPENSHIFT: Create openshift working directory {{ g_credsDir }}"
        file:
          path: "{{ g_credsDir }}"
          mode: "0755"
          state: directory

      - name: "BASTION-OPENSHIFT: Clean-up matchbox ignition directory"
        shell:
          cmd: |
            if [[ -d "/var/lib/matchbox/ignition/" ]] ; then rm -f /var/lib/matchbox/ignition/* ; fi

      ##
      ## Track down the pull secret
      ##
      ##   if    deploying via the ws-deployer, pull_secret may already be deployed
      ##   else  could be in the ./config directory per instructions
      ##   else  this is a manual step user must complete therefore show message and exit
      ##

      - name: "BASTION-OPENSHIFT: maybe find pull-secret in ../config"
        copy:
          src:   "../config/pull-secret.txt" 
          dest:  "{{ g_credsDir }}/pull-secret.txt"
          mode:  "0644"
          owner: root
          group: root
        ignore_errors: yes
    
      - name: "BASTION-OPENSHIFT: maybe find pull-secret in /root"
        copy:
          src:   "/root/{{ g_clusterName }}-pull-secret.txt" 
          dest:  "{{ g_credsDir }}/pull-secret.txt"
          mode:  "0644"
          owner: root
          group: root
          remote_src: yes
        ignore_errors: yes
    
      - name: "BASTION-OPENSHIFT: confirm pull-secret"
        stat: path="{{ g_credsDir }}/pull-secret.txt"
        register: found_secret
    
      - block:
          - debug: msg="RETRIEVE PULL-SECRET https://cloud.redhat.com/openshift/install/metal/user-provisioned"
          - debug: msg="SAVE PULL-SECRET HERE ./config/pull-secret.txt"
          - fail:  msg="MISSING PULL-SECRET"
        when: 
          - found_secret.stat.exists == false
    
      - name: "BASTION-OPENSHIFT: load pull secret"
        shell: cat {{ g_credsDir }}/pull-secret.txt
        register: pull_secret
    
      - name: "BASTION-OPENSHIFT: load ssh key"
        shell: cat /root/.ssh/id_rsa.pub
        register: ssh_key
    
      - name: "BASTION-OPENSHIFT: deploy install-config.yml"
        vars:
          - p_pullSecret:   "{{ pull_secret.stdout |quote }}"
          - p_sshKey:       "{{ ssh_key.stdout |quote }}"
          - p_clusterName:  "{{ g_clusterName }}"
          - p_domain:       "{{ g_publicDomain }}"
          - p_http_proxy:   "{{ g_http_proxy | default ('') }}"
          - p_https_proxy:  "{{ g_https_proxy | default ('') }}"
          - p_no_proxy:     "{{ g_no_proxy | default ('') }}"
        template:
          src: "ocp-install-config.j2"
          dest: "{{ g_credsDir }}/install-config.yaml"
          owner: root
          group: root
          mode: 644
    
      - name: "BASTION-OPENSHIFT: Create a backup of the install-config.yaml"
        shell:
          cmd: |
            cp "{{ g_credsDir }}/install-config.yaml" "{{ g_credsDir }}/install-config.bak"

      - name: "BASTION-OPENSHIFT: create ignition files"
        shell:
          cmd: |
            cd {{ g_credsDir }}
            /usr/local/bin/openshift-install --dir={{ g_credsDir }} create ignition-configs
    
      - name: "BASTION-OPENSHIFT: copy ignition files"
        shell:
          cmd: |
            cp {{ g_credsDir }}/*.ign /var/lib/matchbox/ignition/
    
      - name: "BASTION-OPENSHIFT: fix ignition file permissions"
        shell:
          cmd: |
            chown matchbox.matchbox /var/lib/matchbox/ignition/*

    when:
      - workshop_lock == false

  ## Maybe matchbox needs a refresh of content updates, so just to be safe... restart

  - name: "BASTION-OPENSHIFT: restart matchbox services"
    service: name="{{ item }}" state=restarted enabled=yes daemon_reload=yes
    with_items:
      - "matchbox"
    when: g_useMATCHBOX == "True"

  - name: "BASTION-OPENSHIFT: DEBUG"
    debug: msg="YOU CAN NOW DEPLOY THE BOOTSTRAP"
