---
- hosts: nodes
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:

    ## *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** 
    ##
    ##   We SHOULD use an appropriate perf profile in the real world,
    ##   but we should NEVER enable nobarrier in the real world.
    ##
    ## *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** 
    
    - name: change performance profile                                                                 
      shell:                                                                                           
        cmd: |                                                                                         
          tuned-adm profile virtual-guest                                                              
          mount -o remount,nobarrier /                                                                 

- hosts: masters
  tasks:
  
    - name: "YUM install httpd-utils"
      yum: name=httpd-tools state=installed

- hosts: nodes

  tasks:
  
    - name: "CMD disable yum plugins for rhn and subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/rhnplugin.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf
    
    - name: "USER create and/or reset users"
      user: name="{{ item.name }}" password="{{ item.password }}"
      with_items:
        - {name: 'root', password: '$5$PK7KM9pT$AehNIMYtW22TEE.D0U3ORWCDFMFvARwJLf8YPvVgAf.'}
        - {name: 'student', password: '$5$OJx9uJm8$4VYM2llNxqX/7I4M3vXZM8ZJ9FE2msmHpcOqXlDesC8'}
      
    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-openshift.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

    - name: "YUM install misc required packages"
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,firewalld,lynx state=installed

    - name: "SERVICE STOP firewalld"
      service: name=firewalld state=stopped enabled=yes

    - name: "CMD flushing any existing iptable rules"
      shell: 
        cmd: |
          iptables -F

    - name: "SERVICE START firewalld"
      service: name=firewalld state=started enabled=yes

    - name: "YUM install docker-1.13.1"
      yum: name=docker-1.13.1 state=installed

    - name: "TEMPLATE install /etc/sysconf/docker-storage-setup"
      template:
        src: docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644
      notify: reconfig storage step-1

    - name: "SERVICE ensure docker is stopped"
      service: name=docker state=stopped enabled=yes
      
    - name: "CMD prepare docker storage"
      shell: 
        cmd: |
          rm -f /etc/sysconfig/docker-storage
          rm -rf /var/lib/docker
          vgs docker-vg && vgremove --force docker-vg
          pvs /dev/vdb1 && pvremove --force /dev/vdb1
          wipefs -a /dev/vdb
          
    - name: "CMD configure docker storage"
      shell: 
        cmd: |         
          docker-storage-setup
          
    - name: "SERVICE start docker daemon"
      service: name=docker state=started enabled=yes


