## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: localhost
  tasks:



  ##
  ##    Because the bootstrap disables itself once
  ##    masters are online, test if masters already 
  ##    provide config-service.
  ##



  - name: "ocp4-workshop : deployer-preinstall-masters : test CONFIG SERVER port on masters (if cluster already exists)"
    ignore_errors: true
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5 
      delay: 3
      port: "22623"
      sleep: 1
      state: started
      timeout: 15
    loop: "{{ groups['myMasters'] }}"
    register: config_service_status



  ##
  ##    Masters are not providing config-service, 
  ##    so we need to wait until the bootstrap 
  ##    does provide it
  ##



  - name: "ocp4-workshop : deployer-preinstall-masters : wait for  CONFIG SERVER port on bootstrap"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 3
      port: "22623"
      sleep: 1
      state: started
      timeout: 1800 
    loop: "{{ groups['myBootstrap'] }}"
    when: config_service_status.failed is defined

