## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##     This playbook performs simple task of copying 
##     pull-secret.txt from local config directory to
##     the bastion host.
##
##     Then invoke the workshop playbooks which prepare
##     services on the bastion to support an 
##     Openshift deployment
##

---
- hosts: localhost

  tasks:

  - name: "LIBVIRT-POSTINSTALL-BASTION: stat pull-secret"
    stat: path="../config/pull-secret.txt"
    register: test_pull_secret

  - debug: msg="Pull-Secret URL https://cloud.redhat.com/openshift/install/metal/user-provisioned"
    when: test_pull_secret.stat.exists == false

  - name: "LIBVIRT-POSTINSTALL-BASTION: fail if pull-secret absent"
    fail: msg="COPY YOUR OCP4 PULL-SECRET HERE ./config/pull-secret.txt"
    when: test_pull_secret.stat.exists == false



##
##    Copy the pull secret to bastion server
## 



- hosts: myBastion

  tasks:

  - name: "LIBVIRT-POSTINSTALL-BASTION: Create ssh directory"
    file:
      path: "{{ g_credsDir }}"
      mode: "0700"
      state: directory

  - name: "LIBVIRT-POSTINSTALL-BASTION: deploy pull secret"
    template:
      src: "../config/pull-secret.txt"
      dest: "/root/{{ g_clusterName }}-pull-secret.txt"
      owner: root
      group: root
      mode: 0644



##
##    Now invoke the normal workshop playbook
##



- import_playbook: ocp4-workshop.yml
