---
- hosts: docker

  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:

    - name: "YUM install docker docker-distribution"
      yum: name=docker,docker-distribution state=installed

    - name: "SERVICE stop unwanted services"
      service:
        name:    "{{ item.name }}"
        state:   "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: 'docker',              state: 'stopped', enabled: 'yes' }
        - { name: 'docker-distribution', state: 'stopped', enabled: 'yes' }
        - { name: 'rhel-push-plugin',    state: 'stopped', enabled: 'yes' }
        - { name: 'firewalld',           state: 'stopped', enabled: 'no'  }

    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-docker.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

    - name: "TEMPLATE install /etc/sysconf/docker-storage-setup"
      template:
        src: docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: "CMD prepare docker storage"
      shell:
        cmd: |
          rm -f /etc/sysconfig/docker-storage
          rm -rf /var/lib/docker
          vgs docker-vg && vgremove --force docker-vg
          pvs /dev/vdb1 && pvremove --force /dev/vdb1
          wipefs -a /dev/vdb

    - name: "CMD configure docker storage"
      shell:
        cmd: |
          docker-storage-setup

    - name: "SERVICE start wanted services"
      service:
        name:    "{{ item.name }}"
        state:   "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: 'docker',              state: 'started', enabled: 'yes' }
        - { name: 'docker-distribution', state: 'started', enabled: 'yes' }

    - name: "CMD: Pull rhel7 image"
      shell:
        cmd: |
          docker pull registry.access.redhat.com/rhel7
