---
- hosts: docker

  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:
      
    - name: "CMD disable yum plugins for rhn and subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/rhnplugin.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf
      
    - name: "YUM install docker docker-distribution"
      yum: name=docker,docker-distribution state=installed

    - name: "SERVICE stop unwanted services"
      service:
        name:    "{{ item.name }}"
        state:   "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: 'docker',              state: 'stopped', enabled: 'yes' }
        - { name: 'docker-distribution', state: 'stopped', enabled: 'yes' }
        - { name: 'rhel-push-plugin',    state: 'stopped', enabled: 'yes' }
        - { name: 'firewalld',           state: 'stopped', enabled: 'no'  }

    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-docker.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

    - name: "TEMPLATE install /etc/sysconf/docker-storage-setup"
      template:
        src: docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: "CMD prepare docker storage"
      shell:
        cmd: |
          rm -f /etc/sysconfig/docker-storage
          rm -rf /var/lib/docker
          vgs docker-vg && vgremove --force docker-vg
          pvs /dev/vdb1 && pvremove --force /dev/vdb1
          wipefs -a /dev/vdb

    - name: "CMD configure docker storage"
      shell:
        cmd: |
          docker-storage-setup

    - name: "SERVICE start wanted services"
      service:
        name:    "{{ item.name }}"
        state:   "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: 'docker',              state: 'started', enabled: 'yes' }
        - { name: 'docker-distribution', state: 'started', enabled: 'yes' }

    - name: "CMD: Pull rhel7 image"
      shell:
        cmd: |
          docker pull registry.access.redhat.com/rhel7

    - name: "TEMPLATE install cheat scripts"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - {src: 'cheat-docker-webserver.j2',  dest: '/usr/local/bin/cheat-docker-webserver.sh'}
        - {src: 'cheat-docker-webserver-ro.j2',  dest: '/usr/local/bin/cheat-docker-webserver-ro.sh'}
        - {src: 'cheat-docker-webserver-custom.j2',  dest: '/usr/local/bin/cheat-docker-webserver-custom.sh'}
        - {src: 'cheat-docker-cleanup.j2',  dest: '/usr/local/bin/cheat-docker-cleanup.sh'}
  

- hosts: all

  tasks:

    - name: "TEMPLATE placing docker-install-completed file"
      template:
        src: "install-completed-msg.j2"
        dest: "/root/docker-install-completed.txt"
        owner: root
        group: root
        mode: 0644
