## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost

  tasks:

  - name: "LIBVIRT-DEPLOY-SECRET: stat pull-secret"
    stat: path=../config/ocp4_pull_secret
    register: test_pull_secret

  - debug: msg="Pull-Secret URL https://cloud.redhat.com/openshift/install/metal/user-provisioned"
    when: test_pull_secret.stat.exists == false

  - name: "LIBVIRT-DEPLOY-SECRET: fail is pull-secret absent"
    fail: msg="COPY YOUR OCP4 PULL-SECRET HERE ./config/ocp4_pull_secret"
    when: test_pull_secret.stat.exists == false

- hosts: myBastion

  tasks:

  - name: "LIBVIRT-DEPLOY-SECRET: deploy pull secret"
    template:
      src: "../config/ocp4_pull_secret"
      dest: "/root/ocp4_pull_secret"
      owner: root
      group: root
      mode: 0644
