## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost

  tasks:

  - name: "LIBVIRT-PREINSTALL-WORKERS: Create qcow directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  - name: "LIBVIRT-PREINSTALL-WORKERS: wait for availability of config-server on masters"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 3
      port: 22623
      sleep: 5
      state: started
      timeout: 1800
    loop: "{{ groups['myMasters'] }}"

