## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost

  tasks:

  - name: "LIBVIRT-PREINSTALL-MASTERS: Create qcow directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  - name: "LIBVIRT-PREINSTALL-MASTERS: test CONFIG SERVER port on bootstrap ({{ f_bootstrap_ip }})"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 3
      port: "22623"
      sleep: 1
      state: started
      timeout: 1800 
    loop: "{{ groups['myBootstrap'] }}"

