## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost

  tasks:

  - debug:
      var: vars_libvirt

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - debug:
      var: kvm_cfg

  - debug:
      var: kvm_profiles.bastion

  - debug:
      msg="{{ item }} {{ hostvars[item]['inventory_hostname_short'] }} {{ hostvars[item]['h_pubIP'] }} netmask={{ g_pubNM }} dns={{ g_pubDNS }} gateway={{ g_pubGW }} mac={{ hostvars[item]['h_pubMAC'] }}"
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: virt-install bastion"
    shell:
      cmd: |
        virt-install --name="{{ hostvars[item]['inventory_hostname_short'] }}" \
                     --ram={{ kvm_profiles.bastion.memsize }} \
                     --disk {{ kvm_cfg.qcow_dir}}/{{ hostvars[item]['inventory_hostname_short'] }}.qcow2,bus={{ kvm_profiles.bastion.disk.bus }},sparse={{ kvm_profiles.bastion.disk.sparse }},size={{ kvm_profiles.bastion.disk.size }} \
                     --check disk_size=off \
                     --location={{ kvm_cfg.iso.dir }}/{{ kvm_cfg.iso.name }} \
                     --extra-args="ks={{ kvm_cfg.ks_url }} ip={{ hostvars[item]['h_pubIP'] }} netmask={{ g_pubNM }} dns={{ g_pubDNS }} gateway={{ g_pubGW }}" \
                     --network "network={{ kvm_cfg.network_name }},mac={{ hostvars[item]['h_pubMAC'] }},model={{ kvm_profiles.bastion.network.model }}" \
                     --graphics vnc \
                     --vcpus {{  kvm_profiles.bastion.vcpus }} \
                     --boot hd,network,menu=yes \
                     --noautoconsole
    loop: "{{ groups['myBastion'] }}"
