##
## Moved "workstation" tasks into separate playbook to avoid having a package install/upgrade affect
## a addtional ansible tasks (ie: it potentially breaks the next task execution).  Check the cluster-post-install
## playbook for additional tasks on workshop.example.com
##


- hosts: workstation
  tasks:
  
    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-workstation.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644  

    - name: "SERVICE disable and stop unwanted services"
      service: 
        name="{{ item.name }}"
        state=stopped
        enabled=no
      with_items:
        - {name: 'packagekit'}
        - {name: 'rhsmcertd'}
        - {name: 'libvirtd'}
        - {name: 'dnsmasq'}

    - name: "CMD disable yum plugins for rhn and subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/rhnplugin.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf

    - name: "CMD enable yum  repos for ocp 3.11"
      shell:
        cmd: |
          sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/ose3.11-latest.repo

    - name: "YUM install atomic-openshift-clients plus misc required packages"
      yum: 
        name=atomic-openshift-clients,openshift-ansible,wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,nfs-utils,nfs4-acl-tools,lynx 
        state=installed

