## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook intends to do the heavy lifting of configuring the bastion-host based on the paremeters defined in the
##   ansible inventory (config).
##
##   It will install missing packages, pull (wget) openshift installer, rhcos, etc...
##
## Playbook Assumptions:
##     #1 you are executing this on the bastion-host
##     #2 you have configured and copied ssh-keys to itself.  Meaning, ssh root@localhost works without a password
##     #3 you have completed adjustments to ../configs/ocp4poc-default
##

---
- hosts: myBastion
  tasks:
  


  - name: "BASTION-SETUP: tftp installation"
    yum: name=tftp-server,ipxe-bootimgs,syslinux-tftpboot state=installed
    when: g_usePXE == "True"



  - name: "BASTION-SETUP: tftp create directory"
    when: g_usePXE == "True"
    file:
      path: /var/lib/tftpboot
      mode: "0755"
      state: directory



  - name: "BASTION-SETUP: tftp copy file"
    copy: 
      src: /usr/share/ipxe/undionly.kpxe
      dest: /var/lib/tftpboot
      mode: "0644"
      owner: root
      group: root
      remote_src: yes



  - name: "BASTION-SETUP: tftp restart service"
    when: g_usePXE == "True"
    service: name=tftp state=restarted enabled=yes



  - name: "BASTION-SETUP: tftp firewall service rule"
    when: g_usePXE == "True" 
    firewalld:
      service: tftp
      immediate: yes
      permanent: yes
      state: enabled
