## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook attempts to configure the minimum requirements.  Ideally, to prepare a blueprint you would run
##   this and then snap the blueprint for the workshops.  This playbook is NOT meant for student execution
##
## Playbook Assumptions:
##     #1 you are executing this on the bastion-host
##     #2 your client is registered to RH CDN
##     #3 the following packages have been installed: git, ansible
##

---
- hosts: myBastion
  tasks:
  
  - name: "PREP-BASELINE: install additional packages"
    yum: name=ansible,git,tree,wget,yum-utils state=installed

  - name: "USER create and/or reset users"
    vars:
      - studentName = "student"
    user: name="{{ item.name }}" password="{{ item.password }}"
    with_items:
      - {name: 'root', password: '$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70'}
      - {name: '{{ studentName }}', password: '$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70'}

  - name: "Sudoers Workshop Config"
    vars:
      - studentName = "student"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0600
    with_items:
      - {src: 'sudoers.j2', dest: '/etc/sudoers.d/ocp4-workshop'}

  - name: "PREP-BASELINE: clone repos
    shell: "reposync -l --newest-only --download_path={{ repoDownloadPath }} --repoid={{ item.repoName }}"
    with_items:
      - {repoName: "rhel-8-for-x86_64-baseos-rpms"}
      - {repoName: "rhel-8-for-x86_64-appstreams-rpms"}
      - {repoName: "ansible-2.9-for-rhel-8-x86_64-rpms"}
      
    
    
